import { Collapse } from "antd";
import Styles from "./Resource.module.scss";
import "./style.css";
const text = `
  A dog is a type of domesticated animal.
  Known for its loyalty and faithfulness,
  it can be found as a welcome guest in many households across the world.
`;

const dataElement = (
  <div className={Styles.heading}>
    <h2>INSIDE SALES MANAGER - FREIGHT FORWARDING</h2>
    <h2>Senior Executive</h2>
    <div className={Styles.row}>
      <div className={Styles.column}>
        <div className={Styles.key}>Designation</div>
        <div className={Styles.value}>Senior Executive</div>
      </div>
      <div className={Styles.column}>
        <div className={Styles.key}>Work Experience</div>
        <div className={Styles.value}>Min 2 years</div>
      </div>
      <div className={Styles.column}>
        <div className={Styles.key}>Work Type</div>
        <div className={Styles.value}>Full-Time / On-Site</div>
      </div>
      <div className={Styles.column}>
        <div className={Styles.key}>Work Location</div>
        <div className={Styles.value}>Mumbai (Andheri East)</div>
      </div>
    </div>
  </div>
);

const mainElement = (
  <div className={Styles.main}>
    <div className={Styles.row}>
      <div className={Styles.title}>Key Requirements:</div>
      <div className={Styles.content}>
        <li>
          Bachelor’s degree in any field, preferably Marketing, Business
          Administration, or a related field
        </li>
        <li>
          2+ years of experience in Inside Sales role in Freight Forwarding
        </li>
        <li>
          Strong understanding of import and export processes, Inside Sales
          processes, Incoterms, etc.
        </li>
      </div>
    </div>
    <div className={Styles.row}>
      <div className={Styles.title}>Skills:</div>
      <div className={Styles.content}>
        <li>Ability to influence and communicate effectively with customers</li>
        <li>
          Ensuring high levels of customer satisfaction through excellent
          post-sales service
        </li>
        <li>Excellent communication and interpersonal skills</li>
        <li>Passionate about sales and conversion of prospective leads</li>
        <li>Excellent client relationship management</li>
      </div>
    </div>
    <div className={Styles.row}>
      <div className={Styles.title}>Key Responsibility:</div>
      <div className={Styles.content}>
        <li>
          Conversion of inquiries generated by the sales team and via cold
          calling
        </li>
        <li>Dormant account activation</li>
        <li>Maintaining calling data and conversion records</li>
      </div>
    </div>
  </div>
);
const items = [
  {
    key: "1",
    label: dataElement,
    children: mainElement,
  },
];
const Career = () => {
  const onChange = (key) => {
    console.log(key);
  };
  return (
    <div className={Styles.career}>
      <Collapse
        items={items}
        defaultActiveKey={["1"]}
        onChange={onChange}
        expandIconPosition="end"
        style={{ fontFamily: "Poppins-Regular" }}
      />
      <Collapse
        items={items}
        onChange={onChange}
        expandIconPosition="end"
        style={{ fontFamily: "Poppins-Regular" }}
      />
    </div>
  );
};
export default Career;
