export const mockData = [
  {
    id: 1,
    heading: "Full Truck Load",
    image: "../../images/Home/ourservices/load.png",
    icon: "../../images/Home/ourservices/arrow.png",
    link:"#",
    description: "This card should span the height of two cards.",
  },
  {
    id: 2,
    heading: "Part Truck Load",
    image: "../../images/Home/ourservices/part.png",
    icon: "../../images/Home/ourservices/arrow.png",
    link:"#",
    description: "First card in the second column.",
  },
  {
    id: 3,
    heading: "Express Delivery",
    image: "../../images/Home/ourservices/fast.png",
    icon: "../../images/Home/ourservices/arrow.png",
    link:"#",
    description: "Second card in the second column.",
  },
  {
    id: 4,
    heading: "Exim Movement",
    image: "../../images/Home/ourservices/exim.png",
    icon: "../../images/Home/ourservices/arrow.png",
    link:"#",
    description: "First card in the third column.",
  },
  {
    id: 5,
    heading: "E-Commerce Delivery",
    image: "../../images/Home/ourservices/ecommers.png",
    icon: "../../images/Home/ourservices/arrow.png",
    link:"#",
    description: "Second card in the third column.",
  },
  {
    id: 6,
    heading: "Project Transportation",
    image: "../../images/Home/ourservices/trasportation.png",
    icon: "../../images/Home/ourservices/arrow.png",
    link:"#",
    description: "First card in the fourth column.",
  },
  {
    id: 7,
    heading: "Milk Run",
    image: "../../images/Home/ourservices/milk.png",
    icon: "../../images/Home/ourservices/arrow.png",
    link:"#",
    description: "Second card in the fourth column.",
  },
];

